site_name: Documentation du Projet
site_description: Documentation du projet de génération d'images et de points de contrôle
site_author: Acikoz Yasin & Guillaume Joffrey
site_url: http://127.0.0.1:8000/

# Configuration du répertoire de documentation
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/legrosjojo/gen_img_points_ctrl

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Guide d'utilisation:
    - Interface graphique: usage/gui.md
    - Capture d'images: usage/capture.md
    - Traitement d'images: usage/processing.md
  - API:
    - Module Principal: api/code.md
    - Module de Test: api/test.md
    - Module de Recherche: api/search.md
    - Module de Capture: api/capture.md
    - Module de Reconstruction: api/rebuild.md

use_directory_urls: false 