site_name: Documentation du Projet
site_description: Documentation du projet de génération d'images et de points de contrôle
site_author: Acikoz Yasin & Guillaume Joffrey

# Configuration du répertoire de documentation
docs_dir: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Guide d'utilisation:
    - Interface graphique: usage/gui.md
    - Capture d'images: usage/capture.md
    - Traitement d'images: usage/processing.md
  - API:
    - Module Principal: api/code.md
    - Module de Test: api/test.md
    - Module de Recherche: api/search.md
