site_name: Documentation du Projet FIP
site_description: Documentation du projet de traitement d'images de mires
site_author: Yasin

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation:
    - Interface Graphique: usage/gui.md
  - API:
    - Module Principal: api/code2.md
    - Capture d'Images: api/capture.md
    - Reconstruction: api/rebuild.md
    - Recherche: api/search.md
    - Tests: api/test.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

# Configuration pour GitHub Pages
plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

# Configuration pour le déploiement
repo_url: https://github.com/legrosjojo/gen_img_points_ctrl
repo_name: gen_img_points_ctrl
edit_uri: edit/main/docs/docs/

# Configuration pour GitHub Pages
site_dir: site
