site_name: Documentation du Projet
site_description: Documentation du projet de génération d'images et de points de contrôle
site_author: Acikoz Yasin & Guillaume Joffrey

# Configuration du répertoire de documentation
docs_dir: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  repo_url: https://github.com/legrosjojo/gen_img_points_ctrl

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Guide d'utilisation: usage.md
  - API:
    - Module Principal: api/code.md
    - Module de Test: api/test.md
    - Module de Recherche: api/search.md
